# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Version Checker

on:
  workflow_call:
    
jobs:
  version-checker:
    name: Version Checker
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
        
    - name: Check Project Version
      uses: kzrnm/get-net-sdk-project-versions-action@v1.1.2
      id: get-version
      with:
        proj-path: src/src.csproj
        
    outputs:
      version: ${{ steps.get-version.outputs.version }}
